language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: Pqb+pmqi7RlOrdGTqxbYVFZJtPba1xB0PXNZfQgkzbxWgBCHKQQlZfN3cfZJwkuSiTmGKg3vZ3vYvYd9ALo2BfNzrvBbHQUve3VOy+OUDVwK8oCEzQF4kYGn95200ZIM6+XptJQTJoDJYLHOaRA8xzLwIIJ4d8Vcln8sk9KJbWwGm3gIWscqYBH4xZMYTJd28fTyq5bAzbbGha6y6FvV90ytqarR+abSTXSKwqexMPj032A7BnL6vdpDI3AvtkzLwwuEbwuxNgnrgObVOie9eh3WUrqbnD619lb0JSKTJKLkmPm3XbowWFnxZbTTM183lYZn9l7/mk3j+WoXw0zeNMi0kQJysOD3DWEmMtFAYrgRQib/BrCy8z7oa991QcYOmK6ef+wmSaTmhm93l7aYeAPtinLCoIPdzZBnS/aV4D7UO3goMkorLQJ/qNvkluUL7LFslaUqZ7SpBlBcvsESH2e3Jne8XjY+o/Uf1BUYEDXRItpncpqfxF0Rm+u6CAf4yV+SRfHglv+AlBi77aHpOXe3yj199HNRDxmPO9WDMI6WgEYkOnhzr+xiJzC72b5hJsOc+kE71PFx9vwmFHIYXmr2plWsebawqdn2M+cj8ICynx6bKPMmNE2MLe8i+KrDw+crfqkSlhSIPhRICn5gXRjcKq7Rejsei6cuycFn0Qo=
deploy:
  provider: heroku
  api_key:
    secure: 
tlRDTqIX4txM+ChbzuF4yMBjtXCoq+jf5U5KXkMD37yGkgtIux5BJ2eTyve8rLAd30FFpP1DTCOpBMp+/QV0d502mz+Sy2GiD/Rcx7CM1fIFW4jVKToFeQqk43n6fLCNgJX0YugG6$
  app: intravita-man
  on:
    repo: soker90/Red-Social
